FROM node:18-alpine3.18

WORKDIR /usr/src

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    # Allow install without lockfile, so example works even without Node.js installed locally
    else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
    fi

COPY app ./app
COPY components ./components
COPY data ./data
COPY lib ./lib
COPY providers ./providers
COPY public ./public
COPY middleware.ts .
COPY next.config.js .
COPY postcss.config.js .
COPY tailwind.config.js .
COPY tailwind.config.ts .
COPY tsconfig.json .
COPY .env.local .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
CMD \
    if [ -f package-lock.json ]; then npm run dev; \
    elif [ -f yarn.lock ]; then yarn dev; \
    elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
    else npm run dev; \
    fi