services:
  app:
    image: bcwf-dev
    build:
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env.local
    ports:
      - "3001:3000"
    volumes:
      - ./app:/usr/src/app
      - ./components:/usr/src/components
      - ./data:/usr/src/data
      - ./lib:/usr/src/lib
      - ./providers:/usr/src/providers
      - ./public:/usr/src/public
